# Generated by Django 3.2.5 on 2022-04-04 01:52

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='标题')),
                ('body', models.TextField(blank=True, max_length=10000, verbose_name='正文')),
            ],
        ),
    ]
