# Generated by Django 3.2.5 on 2022-04-04 05:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='abstract',
            field=models.TextField(blank=True, max_length=10000, verbose_name='摘要'),
        ),
    ]
