# Generated by Django 3.2.5 on 2022-04-04 06:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('posts', '0003_alter_post_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': '文章', 'verbose_name_plural': '文章'},
        ),
    ]
