# Generated by Django 3.2 on 2022-04-13 00:42

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_post_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='abstract',
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, max_length=10000, verbose_name='正文'),
        ),
    ]
