# Generated by Django 3.2.5 on 2022-04-04 06:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('meta', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitemeta',
            options={'verbose_name': '站点设置', 'verbose_name_plural': '站点设置'},
        ),
    ]
